### ISSUE TITLE
Feature Request/Suggestion: Change interaction of Condense + Always Show Double

### ISSUE THREAD

**Issue by kaluaabyss** [ThornyFFXI/tCrossBar#10]
When using Always Show Double and Condense To Single behaviors together the result is jarring as the UI elements shift to the center upon pulling L2 or R2.

Suggestion: Instead of moving to the single bar position, remove the opposing triggers visual elements -- leaving the position the same for the pulled trigger's elements. Another option, though I think more complicated, would be to somehow hi-light or pop out the pulled trigger's elements.

**Comment by ThornyFFXI** [comment]
This is a very much personal opinion, other users who rely more heavily on the 3-6th macro sets may be accustomed to looking toward the center of the screen when viewing their current macros.  Feature additions need to be made in a way that they do not make anything worse for existing users.

With that in mind, instead of automatically changing the behavior I have added a combobox to the behavior tab of configuration to allow you to select how you would like LT-RT displayed.  The options are:
'FullDouble' (the full double display)
'HalfDouble' (your current feature request)
'Single' (the single display)

To access this, you'll need to update to 2.09.

**Comment by kaluaabyss** [comment]
Sounds like you captured the spirit of my poorly phrased enhancement request perfectly. Look forward to checking it out later.

Appreciate your work, cheers.
